<?xml version="1.0"?>
<package format="3">
 <name>vikit_common</name>
 <version>0.0.0</version>

 <description>The vikit_common package</description>

 <!-- One maintainer tag required, multiple allowed, one person per tag -->
 <maintainer email="forster@ifi.uzh.ch">cforster</maintainer>

 <!-- One license tag required, multiple allowed, one license per tag -->
 <license>GPLv3</license>

 <!-- Buildtool dependencies -->
 <buildtool_depend>ament_cmake</buildtool_depend>

 <!-- Build dependencies -->
 <build_depend>rclcpp</build_depend>
 <build_depend>libopencv-dev</build_depend>
 <build_depend>eigen</build_depend>
 <build_depend>sophus</build_depend>
 <build_depend>fmt</build_depend>
 
 <!-- Run dependencies -->
 <exec_depend>rclcpp</exec_depend>
 <exec_depend>libopencv-dev</exec_depend>
 <exec_depend>eigen</exec_depend>
 <exec_depend>sophus</exec_depend>
 <exec_depend>fmt</exec_depend>

 <!-- The export tag contains other, unspecified, tags -->
 <export>
   <build_type>ament_cmake</build_type>
 </export>
</package>
